wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
    start_time: 1651109421
    t:
      1:
      - 55
      2:
      - 55
      4: 3.7.3
      5: 0.12.15
      8:
      - 5
